id: PDCEE288D
initial_creation_type: input
source_metadata:
  Title: '-'
  Editor: '-'
  Publisher: '-'
  Place of Publication: '-'
  Year: '-'
  बौद्ध मनीषा- बौद्धेषु प्रमाणमीमांसा:
    Text Version: Devanagari
    Input Personnel: '-'
    Input Date: '2016'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T17:01:07.148327'
last_modified_at: '2022-03-08T17:01:07.148336'
